[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
via_ir = true
optimizer = true
optimizer_runs = 200
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
]

[profile.default.model_checker]
contracts = {}
engine = "chc"
timeout = 10000
targets = ["assert", "underflow", "overflow", "divByZero", "constantCondition", "popEmptyArray", "outOfBounds"]

# Celo Alfajores Testnet configuration
[rpc_endpoints]
alfajores = "https://alfajores-forno.celo-testnet.org"
celo = "https://forno.celo.org"

[etherscan]
alfajores = { key = "${CELOSCAN_API_KEY}", url = "https://alfajores.celoscan.io/api" }
celo = { key = "${CELOSCAN_API_KEY}", url = "https://celoscan.io/api" }